from typing import Protocol

from mastermind_overlay.relics.relic import Relic
from mastermind_overlay.run.gamestate import GameState
from mastermind_overlay.jokers.jokers import Joker


class Renderer(Protocol):
    def dimensions(self) -> tuple[int, int]: ...
    def clear(self) -> None: ...
    def refresh(self) -> None: ...
    def draw_text(self, y: int, x: int, text: str, highlighted: bool = False) -> None: ...
    def render_gameplay(self, state: GameState, stage: int, tier_label: str, relics: list[Relic]) -> None: ...
    def render_win(self, correct_guess_str: str) -> None: ...
    def render_loose(self, correct_guess_str: str) -> None: ...
    def render_run_over(self, selected: int) -> None: ...
    def render_shop(self, currency: int, offer: list[Relic], extra_guess_price: int, selected: int, owned_relics: list[Relic], max_relics: int, reroll_price: int) -> None: ...
    def render_boss_announcement(self, title: str, description: str) -> None: ...
    def render_joker_booster(self, jokers: list[Joker], selected: int) -> None: ...
    def error(self, message: str) -> None: ...
