from typing import Protocol

from mastermind.core.gamestate import GameState
from mastermind.core.relic import Relic


class Renderer(Protocol):
    def dimensions(self) -> tuple[int, int]: ...
    def clear(self) -> None: ...
    def refresh(self) -> None: ...
    def draw_text(self, y: int, x: int, text: str, highlighted: bool = False) -> None: ...
    def render_gameplay(self, state: GameState, ante: int, blind_label: str, relics: list[Relic]) -> None: ...
    def render_win(self, correct_guess_str: str) -> None: ...
    def render_loose(self, correct_guess_str: str) -> None: ...
    def render_shop(self, currency: int, offer: list[Relic], extra_guess_price: int, selected: int, owned_relics: list[Relic], max_relics: int) -> None: ...
